version: '3.4'

services:
  db:
    image: projeto_gabriel-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3308:3306
    networks:
      - gsystem-network
    volumes:
      - db_data:/var/lib/mysql

  projeto_gabriel:
    image: projeto_gabriel
    build:
      context: .
      dockerfile: Projeto_Gabriel/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
      MYSQLCONNECTION__MYSQLCONNECTIONSTRING: "Server=db;DataBase=${MYSQL_DATABASE};Uid=${MYSQL_USER};Pwd=${MYSQL_PASSWORD};SslMode=none;"
    ports:
      - 44300:8080
      - 4430:8081
    depends_on:
      - db
    networks:
      - gsystem-network

  client:
    image: projeto_gabriel-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:80
    networks:
      - gsystem-network

networks:
  gsystem-network:
    driver: bridge

volumes:
  db_data: # Define o volume persistente para o banco de dados
